version: '3.8'
services:
  web:
    build: ./project
    command: >
      /bin/sh -c "python3 manage.py makemigrations --force-color --no-input -v 3
      && python3 manage.py makemigrations --merge --no-input -v 3
      && python3 manage.py migrate --force-color -v 3
      && python3 manage.py createsuperuser --noinput; exit 0"
      Источник: https://egorovegor.ru/python-docker-django
    volumes:
      - ./project:/usr/src/app

    ports:
      - "8000:8000"
    env_file:
      - .env.dev
#    depends_on:
#      - db

#  db:
#    image: postgres
#    restart: always
#    ports:
#      - "5432:5432"
#    env_file:
#      - .env.db
