version: '3.8'
services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:./backend

    ports:
      - "8000:8000"
    env_file:
      - .env
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.db