import styles from './stickers.module.scss';

/* eslint-disable-next-line */
export interface StickersProps {}

export const STICKERS = [
  { uuid: 'random-uuid-10', identificator: '🥳', name: 'celebration', emoji: '🥳' },
  { uuid: 'random-uuid-11', identificator: '⌨️', name: 'keyboard', emoji: '⌨️' },
  { uuid: 'random-uuid-12', identificator: '⏳', name: 'hourglass', emoji: '⏳' },
  { uuid: 'random-uuid-13', identificator: '☃️', name: 'snowman', emoji: '☃️' },
  { uuid: 'random-uuid-14', identificator: '☺️', name: 'smile', emoji: '☺️' },
  { uuid: 'random-uuid-15', identificator: '❌', name: 'cross mark', emoji: '❌' },
  { uuid: 'random-uuid-16', identificator: '❣️', name: 'heart exclamation', emoji: '❣️' },
  { uuid: 'random-uuid-17', identificator: '❤️', name: 'heart', emoji: '❤️' },
  { uuid: 'random-uuid-18', identificator: '🎂', name: 'birthday cake', emoji: '🎂' },
  { uuid: 'random-uuid-19', identificator: '🎄', name: 'Christmas tree', emoji: '🎄' },
  { uuid: 'random-uuid-20', identificator: '🎊', name: 'confetti ball', emoji: '🎊' },
  { uuid: 'random-uuid-21', identificator: '🎮', name: 'video game', emoji: '🎮' },
  { uuid: 'random-uuid-22', identificator: '👨‍⚕️', name: 'man health worker', emoji: '👨‍⚕️' },
  { uuid: 'random-uuid-23', identificator: '👨‍🏫', name: 'man teacher', emoji: '👨‍🏫' },
  { uuid: 'random-uuid-24', identificator: '👩‍⚕️', name: 'woman health worker', emoji: '👩‍⚕️' },
  { uuid: 'random-uuid-25', identificator: '👻', name: 'ghost', emoji: '👻' },
  { uuid: 'random-uuid-26', identificator: '👿', name: 'angry face with horns', emoji: '👿' },
  { uuid: 'random-uuid-27', identificator: '💀', name: 'skull', emoji: '💀' },
  { uuid: 'random-uuid-28', identificator: '💊', name: 'pill', emoji: '💊' },
  { uuid: 'random-uuid-29', identificator: '💋', name: 'kiss mark', emoji: '💋' },
  { uuid: 'random-uuid-30', identificator: '💌', name: 'love letter', emoji: '💌' },
  { uuid: 'random-uuid-31', identificator: '💎', name: 'gem', emoji: '💎' },
  { uuid: 'random-uuid-32', identificator: '💓', name: 'beating heart', emoji: '💓' },
  { uuid: 'random-uuid-33', identificator: '💔', name: 'broken heart', emoji: '💔' },
  { uuid: 'random-uuid-34', identificator: '💕', name: 'two hearts', emoji: '💕' },
  { uuid: 'random-uuid-35', identificator: '💖', name: 'sparkling heart', emoji: '💖' },
  { uuid: 'random-uuid-36', identificator: '💗', name: 'growing heart', emoji: '💗' },
  { uuid: 'random-uuid-37', identificator: '💘', name: 'heart with arrow', emoji: '💘' },
  { uuid: 'random-uuid-38', identificator: '💙', name: 'blue heart', emoji: '💙' },
  { uuid: 'random-uuid-39', identificator: '💚', name: 'green heart', emoji: '💚' },
  { uuid: 'random-uuid-40', identificator: '💛', name: 'yellow heart', emoji: '💛' },
  { uuid: 'random-uuid-41', identificator: '💜', name: 'purple heart', emoji: '💜' },
  { uuid: 'random-uuid-42', identificator: '💝', name: 'heart with ribbon', emoji: '💝' },
  { uuid: 'random-uuid-43', identificator: '💞', name: 'revolving hearts', emoji: '💞' },
  { uuid: 'random-uuid-44', identificator: '💡', name: 'light bulb', emoji: '💡' },
  { uuid: 'random-uuid-45', identificator: '💯', name: 'hundred points', emoji: '💯' },
  { uuid: 'random-uuid-46', identificator: '💸', name: 'money', emoji: '💸' },
  { uuid: 'random-uuid-47', identificator: '📁', name: 'folder', emoji: '📁' },
  { uuid: 'random-uuid-48', identificator: '📂', name: 'open folder', emoji: '📂' },
  { uuid: 'random-uuid-49', identificator: '📝', name: 'memo', emoji: '📝' },
  { uuid: 'random-uuid-50', identificator: '📣', name: 'announcement', emoji: '📣' },
  { uuid: 'random-uuid-51', identificator: '📭', name: 'mailbox', emoji: '📭' },
  { uuid: 'random-uuid-52', identificator: '🔐', name: 'locked', emoji: '🔐' },
  { uuid: 'random-uuid-53', identificator: '🔥', name: 'fire', emoji: '🔥' },
  { uuid: 'random-uuid-54', identificator: '🖤', name: 'black heart', emoji: '🖤' },
  { uuid: 'random-uuid-55', identificator: '🗂️', name: 'file folder', emoji: '🗂️' },
  { uuid: 'random-uuid-56', identificator: '😀', name: 'grinning', emoji: '😀' },
  { uuid: 'random-uuid-57', identificator: '😁', name: 'grin', emoji: '😁' },
  { uuid: 'random-uuid-58', identificator: '😃', name: 'smile', emoji: '😃' },
  { uuid: 'random-uuid-59', identificator: '😄', name: 'happy', emoji: '😄' },
  { uuid: 'random-uuid-60', identificator: '😅', name: 'laughing', emoji: '😅' },
  { uuid: 'random-uuid-61', identificator: '😆', name: 'grin squint', emoji: '😆' },
  { uuid: 'random-uuid-62', identificator: '😇', name: 'angelic', emoji: '😇' },
  { uuid: 'random-uuid-63', identificator: '😈', name: 'devilish', emoji: '😈' },
  { uuid: 'random-uuid-64', identificator: '🥳', name: 'celebration', emoji: '🥳' },
  { uuid: 'random-uuid-65', identificator: '😉', name: 'sticker', emoji: '😉' },
  { uuid: 'random-uuid-66', identificator: '😊', name: 'sticker', emoji: '😊' },
  { uuid: 'random-uuid-67', identificator: '😋', name: 'sticker', emoji: '😋' },
  { uuid: 'random-uuid-68', identificator: '😌', name: 'sticker', emoji: '😌' },
  { uuid: 'random-uuid-69', identificator: '😍', name: 'sticker', emoji: '😍' },
  { uuid: 'random-uuid-70', identificator: '😎', name: 'sticker', emoji: '😎' },
  { uuid: 'random-uuid-71', identificator: '😏', name: 'sticker', emoji: '😏' },
  { uuid: 'random-uuid-72', identificator: '😐', name: 'sticker', emoji: '😐' },
  { uuid: 'random-uuid-73', identificator: '😑', name: 'sticker', emoji: '😑' },
  { uuid: 'random-uuid-74', identificator: '😒', name: 'sticker', emoji: '😒' },
  { uuid: 'random-uuid-75', identificator: '😔', name: 'sticker', emoji: '😔' },
  { uuid: 'random-uuid-76', identificator: '😕', name: 'sticker', emoji: '😕' },
  { uuid: 'random-uuid-77', identificator: '😗', name: 'sticker', emoji: '😗' },
  { uuid: 'random-uuid-78', identificator: '😘', name: 'sticker', emoji: '😘' },
  { uuid: 'random-uuid-79', identificator: '😙', name: 'sticker', emoji: '😙' },
  { uuid: 'random-uuid-80', identificator: '😚', name: 'sticker', emoji: '😚' },
  { uuid: 'random-uuid-81', identificator: '😛', name: 'sticker', emoji: '😛' },
  { uuid: 'random-uuid-82', identificator: '😜', name: 'sticker', emoji: '😜' },
  { uuid: 'random-uuid-83', identificator: '😝', name: 'sticker', emoji: '😝' },
  { uuid: 'random-uuid-84', identificator: '🥳', name: 'celebration', emoji: '🥳' },
  { uuid: 'random-uuid-85', identificator: '😞', name: 'sad', emoji: '😞' },
  { uuid: 'random-uuid-86', identificator: '😟', name: 'worried', emoji: '😟' },
  { uuid: 'random-uuid-87', identificator: '😡', name: 'angry', emoji: '😡' },
  { uuid: 'random-uuid-88', identificator: '😢', name: 'crying', emoji: '😢' },
  { uuid: 'random-uuid-89', identificator: '😤', name: 'frustrated', emoji: '😤' },
  { uuid: 'random-uuid-90', identificator: '😦', name: 'surprised', emoji: '😦' },
  { uuid: 'random-uuid-91', identificator: '😧', name: 'shocked', emoji: '😧' },
  { uuid: 'random-uuid-92', identificator: '😫', name: 'tired', emoji: '😫' },
  { uuid: 'random-uuid-93', identificator: '😬', name: 'awkward', emoji: '😬' },
  { uuid: 'random-uuid-94', identificator: '😭', name: 'weeping', emoji: '😭' },
  { uuid: 'random-uuid-95', identificator: '😮', name: 'astonished', emoji: '😮' },
  { uuid: 'random-uuid-96', identificator: '😯', name: 'amazed', emoji: '😯' },
  { uuid: 'random-uuid-97', identificator: '😱', name: 'terrified', emoji: '😱' },
  { uuid: 'random-uuid-98', identificator: '😲', name: 'astonished', emoji: '😲' },
  { uuid: 'random-uuid-99', identificator: '😳', name: 'flushed', emoji: '😳' },
  { uuid: 'random-uuid-100', identificator: '😴', name: 'sleepy', emoji: '😴' },
  { uuid: 'random-uuid-101', identificator: '😶', name: 'silent', emoji: '😶' },
  { uuid: 'random-uuid-102', identificator: '😷', name: 'masked', emoji: '😷' },
  { uuid: 'random-uuid-103', identificator: '😸', name: 'grinning cat', emoji: '😸.gif' },
  { uuid: 'random-uuid-104', identificator: '😹', name: 'crying cat', emoji: '😹.gif' },
  { uuid: 'random-uuid-105', identificator: '😺', name: 'smiling cat', emoji: '😺.gif' },
  { uuid: 'random-uuid-106', identificator: '😻', name: 'heart eyes cat', emoji: '😻.gif' },
  { uuid: 'random-uuid-107', identificator: '😼', name: 'smirking cat', emoji: '😼.gif' },
  { uuid: 'random-uuid-108', identificator: '😽', name: 'kissing cat', emoji: '😽.gif' },
  { uuid: 'random-uuid-109', identificator: '😾', name: 'pouting cat', emoji: '😾.gif' },
  { uuid: 'random-uuid-110', identificator: '😿', name: 'crying cat', emoji: '😿.gif' },
  { uuid: 'random-uuid-111', identificator: '🙀', name: 'weary cat', emoji: '🙀.gif' },
  { uuid: 'random-uuid-112', identificator: '🙂', name: 'slightly smiling face', emoji: '🙂.gif' },
  { uuid: 'random-uuid-113', identificator: '🙃', name: 'upside-down face', emoji: '🙃.gif' },
  { uuid: 'random-uuid-114', identificator: '🙄', name: 'rolling eyes face', emoji: '🙄.gif' },
  { uuid: 'random-uuid-115', identificator: '🙈', name: 'see-no-evil monkey', emoji: '🙈.gif' },
  { uuid: 'random-uuid-116', identificator: '🙊', name: 'speak-no-evil monkey', emoji: '🙊.gif' },
  { uuid: 'random-uuid-117', identificator: '🤍', name: 'white heart', emoji: '🤍.gif' },
  { uuid: 'random-uuid-118', identificator: '🤎', name: 'brown heart', emoji: '🤎.gif' },
  { uuid: 'random-uuid-119', identificator: '🤑', name: 'money-mouth face', emoji: '🤑.gif' },
  { uuid: 'random-uuid-120', identificator: '🤒', name: 'sick face', emoji: '🤒.gif' },
  { uuid: 'random-uuid-121', identificator: '🤓', name: 'nerd', emoji: '🤓.gif' },
  { uuid: 'random-uuid-122', identificator: '🤔', name: 'thinking', emoji: '🤔.gif' },
  { uuid: 'random-uuid-123', identificator: '🤕', name: 'hurt', emoji: '🤕.gif' },
  { uuid: 'random-uuid-124', identificator: '🤖', name: 'robot', emoji: '🤖.gif' },
  { uuid: 'random-uuid-125', identificator: '🤢', name: 'sick', emoji: '🤢.gif' },
  { uuid: 'random-uuid-126', identificator: '🤣', name: 'laughing', emoji: '🤣.gif' },
  { uuid: 'random-uuid-127', identificator: '🤤', name: 'drooling', emoji: '🤤.gif' },
  { uuid: 'random-uuid-128', identificator: '🤧', name: 'sneezing', emoji: '🤧.gif' },
  { uuid: 'random-uuid-129', identificator: '🤪', name: 'crazy', emoji: '🤪.gif' },
  { uuid: 'random-uuid-130', identificator: '🤫', name: 'shushing', emoji: '🤫.gif' },
  { uuid: 'random-uuid-131', identificator: '🤬', name: 'angry', emoji: '🤬.gif' },
  { uuid: 'random-uuid-132', identificator: '🤭', name: 'giggling', emoji: '🤭.gif' },
  { uuid: 'random-uuid-133', identificator: '🤮', name: 'vomiting', emoji: '🤮.gif' },
  { uuid: 'random-uuid-134', identificator: '🤯', name: 'mind-blown', emoji: '🤯.gif' },
  { uuid: 'random-uuid-135', identificator: '🤷‍♀️', name: 'woman-shrugging', emoji: '🤷‍♀️.gif' },
  { uuid: 'random-uuid-136', identificator: '🤷‍♂️', name: 'man-shrugging', emoji: '🤷‍♂️.gif' },
  { uuid: 'random-uuid-137', identificator: '🥰', name: 'heart-eyes', emoji: '🥰.gif' },
  { uuid: 'random-uuid-138', identificator: '🥱', name: 'yawning', emoji: '🥱.gif' },
  { uuid: 'random-uuid-139', identificator: '🥲', name: 'teary', emoji: '🥲.gif' },
  { uuid: 'random-uuid-140', identificator: '🥳', name: 'celebration', emoji: '🥳.gif' },
  { uuid: 'random-uuid-141', identificator: '🥴', name: 'woozy', emoji: '🥴.gif' },
  { uuid: 'random-uuid-142', identificator: '🥳', name: 'celebration', emoji: '🥳' },
  { uuid: 'random-uuid-143', identificator: '🥵', name: 'hot', emoji: '🥵' },
  { uuid: 'random-uuid-144', identificator: '🥶', name: 'cold', emoji: '🥶' },
  { uuid: 'random-uuid-145', identificator: '🥸', name: 'disguise', emoji: '🥸' },
  { uuid: 'random-uuid-146', identificator: '🥺', name: 'pleading', emoji: '🥺' },
  { uuid: 'random-uuid-147', identificator: '🦠', name: 'microbe', emoji: '🦠' },
  { uuid: 'random-uuid-148', identificator: '🧐', name: 'curious', emoji: '🧐' },
  { uuid: 'random-uuid-149', identificator: '🧡', name: 'orange-heart', emoji: '🧡' },
  { uuid: 'random-uuid-150', identificator: '🧭', name: 'compass', emoji: '🧭' },
  { uuid: 'random-uuid-151', identificator: '🧻', name: 'toilet-paper', emoji: '🧻' },
  { uuid: 'random-uuid-152', identificator: '🧼', name: 'soap', emoji: '🧼' },
  { uuid: 'random-uuid-153', identificator: '🧽', name: 'sponge', emoji: '🧽' },
];

export function getStickerByUUID(uuid: string) {
  return STICKERS.find(sticker => sticker.uuid === uuid);
}

export function Stickers(props: StickersProps) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to Stickers!</h1>
    </div>
  );
}

export default Stickers;
