# Generated by Django 5.0.4 on 2024-04-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='service',
            field=models.ManyToManyField(to='dashboard.service'),
        ),
    ]
