# Generated by Django 5.0.4 on 2024-04-20 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='general',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.owner'),
        ),
        migrations.AddField(
            model_name='review',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.consumer'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='reviews',
            field=models.ManyToManyField(to='dashboard.review'),
        ),
        migrations.AddField(
            model_name='beach',
            name='reviews',
            field=models.ManyToManyField(to='dashboard.review'),
        ),
        migrations.AddField(
            model_name='service',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.facility'),
        ),
        migrations.AddField(
            model_name='loyality',
            name='services',
            field=models.ManyToManyField(to='dashboard.service'),
        ),
        migrations.AddField(
            model_name='stock',
            name='services',
            field=models.ManyToManyField(to='dashboard.service'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.consumer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
        ),
        migrations.AddField(
            model_name='travel',
            name='facilitys',
            field=models.ManyToManyField(blank=True, to='dashboard.facility'),
        ),
        migrations.AddField(
            model_name='travel',
            name='general',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.general'),
        ),
        migrations.AddField(
            model_name='travel',
            name='reviews',
            field=models.ManyToManyField(to='dashboard.review'),
        ),
        migrations.AddField(
            model_name='valley',
            name='general',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.general'),
        ),
        migrations.AddField(
            model_name='valley',
            name='reviews',
            field=models.ManyToManyField(to='dashboard.review'),
        ),
    ]
