# Generated by Django 5.0.4 on 2024-04-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_general_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterField(
            model_name='event',
            name='general',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.general'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='general',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.general'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='general',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.general'),
        ),
    ]
