# Generated by Django 5.0.4 on 2024-04-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_service_stock_stock_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='service',
            new_name='services',
        ),
    ]
