# Generated by Django 5.0.4 on 2024-04-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_service_loyality_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default='2022-01-01'),
        ),
    ]
